name: 🚀 Deploy ReadMind Dev (Internal Test)

on:
  push:
    branches:
      - qa   # Se ejecuta cuando haces merge de 'dev' a 'qa'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Descarga el código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configura Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'  # Ajusta a tu versión actual
          channel: 'stable'

      # 3️⃣ Instala dependencias
      - name: Install dependencies
        run: flutter pub get

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_FILE_BASE64 }}" | base64 --decode > android/app/my-release-key.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=my-release-key.jks" >> android/key.properties

      # 4️⃣ Compila el .aab del flavor dev
      - name: Build appbundle (dev)
        run: flutter build appbundle --flavor dev --release

      - name: List built files
        run: ls -l build/app/outputs/bundle/devRelease/

      - name: Decode Play Store JSON key
        run: echo "${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_JSON }}" > /tmp/playstore_key.json

      - name: Upload to Google Play (Internal)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: /tmp/playstore_key.json
          packageName: com.readmind.dev
          releaseFiles: build/app/outputs/bundle/devRelease/app-dev-release.aab
          track: internal
          status: completed